#!/usr/bin/env node
/**
 * setup-env.js — Environment setup for arxiv-daily-review
 *
 * Usage: node scripts/setup-env.js --root <dir> [--category <cat>] [--max-papers <N>] [--direction <text>]
 *
 * Responsibilities:
 *   1. Check Node.js availability
 *   2. Check pi CLI availability
 *   3. Collect/verify API key
 *   4. Write .agent.env with all variables needed by subsequent phases
 *
 * Exit codes: 0 = ready, 1 = missing required input, 2 = dependency not found
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ── Argument parsing ──
function parseArgs(argv) {
  const args = { root: process.cwd() };
  for (let i = 2; i < argv.length; i++) {
    const k = argv[i], v = argv[i + 1];
    if (k === '--root' && v) { args.root = path.resolve(v); i++; }
    else if (k === '--category' && v) { args.category = v; i++; }
    else if (k === '--max-papers' && v) { args.maxPapers = parseInt(v, 10); i++; }
    else if (k === '--direction' && v) { args.direction = v; i++; }
  }
  return args;
}

function main() {
  const args = parseArgs(process.argv);
  const envPath = path.join(args.root, '.agent.env');

  console.log('[setup-env] Checking environment for arxiv-daily-review...\n');

  // Step 1: Check Node.js
  try {
    const ver = execSync('node --version', { encoding: 'utf-8' }).trim();
    console.log(`[✓] Node.js: ${ver}`);
  } catch {
    console.error('[✗] Node.js not found. Install via: curl -fsSL https://fnm.vercel.app/install | bash');
    process.exit(2);
  }

  // Step 2: Check pi CLI
  try {
    const ver = execSync('pi --version', { encoding: 'utf-8', stdio: ['pipe','pipe','pipe'] }).trim();
    console.log(`[✓] pi CLI: ${ver}`);
  } catch {
    console.error('[✗] pi CLI not found. Install via: npm install -g @earendil-works/pi-coding-agent');
    process.exit(2);
  }

  // Step 3: Collect configuration
  const category = args.category || process.env.ARXIV_CATEGORY || 'cs.AI';
  const maxPapers = args.maxPapers || parseInt(process.env.MAX_PAPERS || '20', 10);
  const direction = args.direction || process.env.RESEARCH_DIRECTION || 'LLM Agent';
  const model = process.env.MODEL || process.env.PI_MODEL || 'pi-default';
  const apiKey = process.env.API_KEY || process.env.ANTHROPIC_API_KEY || process.env.OPENAI_API_KEY || '';

  // Step 4: Ensure output directory exists
  const outputDir = path.join(args.root, 'daily-reports');
  fs.mkdirSync(outputDir, { recursive: true });

  // Step 5: Write .agent.env (one-shot — all variables all phases need)
  const envLines = [
    `# arxiv-daily-review environment — generated by setup-env.js at ${new Date().toISOString()}`,
    `MODEL=${model}`,
    `ARXIV_CATEGORY=${category}`,
    `MAX_PAPERS=${maxPapers}`,
    `RESEARCH_DIRECTION=${direction}`,
    `PROJECT_DIR=${path.resolve(args.root)}`,
    `OUTPUT_DIR=${outputDir}`,
    `ARXIV_API_BASE=https://export.arxiv.org/api/query`,
    '',
    '# Set your API key here if not exported in shell:',
    `API_KEY=${apiKey}`,
    '',
    '# Scope variables (optional — for incremental runs):',
    '# ARXIV_DATE_RANGE=2025-01-10:2025-01-15  (YYYY-MM-DD:YYYY-MM-DD format)',
    '# ARXIV_SPECIFIC_IDS=2301.12345,2301.12346   (comma-separated arxiv IDs, bypasses search)',
  ];

  fs.writeFileSync(envPath, envLines.join('\n'), 'utf-8');
  console.log(`[✓] Wrote .agent.env to ${envPath}`);
  console.log(`    Category: ${category}`);
  console.log(`    Max papers: ${maxPapers}`);
  console.log(`    Research direction: ${direction}`);
  console.log(`    Model: ${model}`);
  console.log(`    Output: ${outputDir}`);
  console.log('\n[setup-env] Ready. Run discover.js next (Phase 1).');
}

main();