#!/usr/bin/env node
/**
 * setup-env.js — Environment setup for ashare-research
 *
 * Usage: node scripts/setup-env.js --root <dir> [--targets <list>] [--days <N>] [--focus <text>]
 *
 * Targets format: "secid:名称" comma-separated, e.g. "1.000001:上证指数,0.399001:深证成指"
 *
 * Exit codes: 0 = ready, 2 = dependency not found
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ── Argument parsing ──
function parseArgs(argv) {
  const args = { root: process.cwd() };
  for (let i = 2; i < argv.length; i++) {
    const k = argv[i], v = argv[i + 1];
    if (k === '--root' && v) { args.root = path.resolve(v); i++; }
    else if (k === '--targets' && v) { args.targets = v; i++; }
    else if (k === '--days' && v) { args.days = parseInt(v, 10); i++; }
    else if (k === '--focus' && v) { args.focus = v; i++; }
  }
  return args;
}

function main() {
  const args = parseArgs(process.argv);
  const envPath = path.join(args.root, '.agent.env');

  console.log('[setup-env] Checking environment for ashare-research...\n');

  // Step 1: Check Node.js
  try {
    const ver = execSync('node --version', { encoding: 'utf-8' }).trim();
    console.log(`[✓] Node.js: ${ver}`);
  } catch {
    console.error('[✗] Node.js not found.');
    process.exit(2);
  }

  // Step 2: Check pi CLI
  try {
    const ver = execSync('pi --version', { encoding: 'utf-8', stdio: ['pipe','pipe','pipe'] }).trim();
    console.log(`[✓] pi CLI: ${ver}`);
  } catch {
    console.error('[✗] pi CLI not found. Install via: npm install -g @earendil-works/pi-coding-agent');
    process.exit(2);
  }

  // Step 3: Collect configuration
  const targets = args.targets || process.env.ASHARE_TARGETS || '1.000001:上证指数,0.399001:深证成指,0.399006:创业板指';
  const days = args.days || parseInt(process.env.LOOKBACK_DAYS || '30', 10);
  const focus = args.focus || process.env.ANALYSIS_FOCUS || '趋势与关键位';
  const model = process.env.MODEL || process.env.PI_MODEL || 'pi-default';

  // Step 4: Ensure output directory exists
  const outputDir = path.join(args.root, 'reports');
  fs.mkdirSync(outputDir, { recursive: true });

  // Step 5: Write .agent.env
  const envLines = [
    `# ashare-research environment — generated by setup-env.js at ${new Date().toISOString()}`,
    `MODEL=${model}`,
    `TARGETS=${targets}`,
    `LOOKBACK_DAYS=${days}`,
    `ANALYSIS_FOCUS=${focus}`,
    `PROJECT_DIR=${path.resolve(args.root)}`,
    `OUTPUT_DIR=${outputDir}`,
    `API_BASE=https://push2his.eastmoney.com/api/qt/stock/kline/get`,
    '',
    '# Common secids: 1.000001 上证指数 | 0.399001 深证成指 | 0.399006 创业板指',
    '# 沪市个股前缀 1（如 1.600519 贵州茅台），深市个股前缀 0（如 0.000001 平安银行）',
  ];

  fs.writeFileSync(envPath, envLines.join('\n'), 'utf-8');
  console.log(`[✓] Wrote .agent.env to ${envPath}`);
  console.log(`    Targets: ${targets}`);
  console.log(`    Lookback: ${days} days`);
  console.log(`    Focus: ${focus}`);
  console.log(`    Model: ${model}`);
  console.log(`    Output: ${outputDir}`);
  console.log('\n[setup-env] Ready. Run discover.js next (Phase 1).');
}

main();
